fname_data_parquet: data/training/GLODAPv2023-raw_collocated-{y}.pq
yname_target: talk
xname_features:
- salinity
- temperature
- nitrate
- bottomdepth
num_cv_folds: 5


params:

- model_name: "CatBoost"
  default_kwargs: { train_dir: models/catboost_cv_train_info }
  param_grid:
    n_estimators: [ 2 3 5 ]
    depth: [ 10 ]
    border_count: [ 512 ]

- model_name: "LightGBM"
  param_grid:
    n_estimators: [ 1 2 3]
    num_leaves: [ 32 ]
    min_child_samples: [ 10 ]

- model_name: "RandomForest"
  param_grid:
    n_estimators: [ 1 3 5 ]
    max_depth: [ 20 ]
    min_samples_leaf: [ 10 ]
