fname_data_parquet: data/training/GLODAPv2023-raw_collocated-{y}.pq
yname_target: talk_normalized
xname_features:
- salinity
- temperature
num_cv_folds: 5

params:
- model_name: "RandomForest"
  param_grid:
  - n_estimators: [ 100, 500, 1000 ]
  - max_depth: [ 10, 20, 50 ]
  - min_samples_leaf: [ 5, 10, 20 ]
- model_name: "CatBoost"
  param_grid:
  - n_iterations: [ 1000, 2000 ]
